### Feature extarction for each province
- Here we'll observe the data structure and extract important features 
- Budget and expenditure will be separated

| Attribute Name | Category        | Meaning and Context                                                                                                                                                      |
|----------------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| SN             | Identifier      | Serial Number or Sl. No. A simple numerical index to count the entries (local bodies/rows).                                                                              |
| Local Body     | Identifier      | The name of the specific local government unit (e.g., Municipality, Rural Municipality, District Coordination Committee) whose financial data is being reported.           |
| Recurrent      | Budget/Expenditure | Spending on day-to-day operations and administrative costs that recur every year. This includes salaries, office supplies, utilities, maintenance, and regular subsidies. |
| Capital        | Budget/Expenditure | Spending on creating or acquiring long-term assets. This is investment spending, such as building roads, schools, hospitals, water systems, or purchasing land and heavy machinery. |
| Financial      | Budget/Expenditure | Spending related to financial transactions. This often includes interest payments on loans, principal loan repayments, and other financial liabilities.                    |
| Total          | Summary         | The sum of the respective Recurrent, Capital, and Financial categories. Since you have two sets of these (Recurrent, Capital, Financial, Total), this column represents the Total Budget or Total Expenditure. |
| Cash Balance   | Balance         | The closing balance of cash or bank reserves at the end of the reporting period (e.g., end of the fiscal year) after all expenditures have been accounted for.               |

In [8]:
import pandas as pd

In [9]:
!pip install openpyxl

zsh: command NOT found: 'fastfetch.sh'
Requirement already satisfied: openpyxl in /home/khagendra/ai_ml_env/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/khagendra/ai_ml_env/lib/python3.13/site-packages (from openpyxl) (2.0.0)

In [10]:
df = pd.read_excel("../data/Expenditure-of-local-bodies.xlsx", skiprows=3)

In [11]:
df

,Province 1,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Phungling Municipality,38.550184,26.144191,0.000000,64.694376,34.104109,24.514032,0.000000,58.618140,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.792690,22.705015,0.000000,49.497705,21.729910,13.335082,0.000000,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.000000,46.095307,24.071506,12.591538,0.000000,36.663044,7.179870
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.000000,31.745256,16.349711,8.581009,0.000000,24.930720,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.000000,42.674779,23.587589,15.188281,0.000000,38.775871,2.881517
...,...,...,...,...,...,...,...,...,...,...,...
762,751,Joshipur Rural Municipality,32.747868,23.846230,0.000000,56.594098,27.279500,17.450748,0.000000,44.730248,8.309407
763,752,Bardgoria Rural Municipality,29.301354,18.072167,0.000000,47.373521,24.572328,10.642243,0.000000,35.214571,8.282966
764,753,Mohanyal Rural Municipality,31.348901,19.733100,0.000000,51.082001,27.424238,17.111610,0.000000,44.535848,4.147401
765,Sudurpaschim Province Total,NaN,3062.187398,2068.968939,0.423100,5131.579438,2667.222757,1559.780752,0.405687,4227.409196,544.253354
766,Grand Total,NaN,28817.041524,24415.999125,65.324974,53298.365623,23487.310176,15629.985685,26.332561,39143.628422,10156.757357

In [12]:
df["Unnamed: 1"]

0                  Phungling Municipality
1      Aathrai Tribeni Rural Municipality
2        Phaktanglung  Rural Municipality
3          Mikwakhola  Rural Municipality
4           Meringdeng Rural Municipality
                      ...
762           Joshipur Rural Municipality
763          Bardgoria Rural Municipality
764           Mohanyal Rural Municipality
765                                   NaN
766                                   NaN
Name: Unnamed: 1, Length: 767, dtype: object

In [13]:
len(list(df["Unnamed: 1"]))

767

In [14]:
df = df.fillna('')

In [15]:
rename_dict = {
    "Province 1" : "SN",
    "Unnamed: 1" : "Local Body",
    "Unnamed: 2" : "Recurrent",
    "Unnamed: 3" : "Capital",
    "Unnamed: 4" : "Financial",
    "Unnamed: 5" : "Total",
    "Unnamed: 6" : "Recurrent",
    "Unnamed: 7" : "Capital",
    "Unnamed: 8" : "Financial",
    "Unnamed: 9" : "Total",
    "Unnamed: 10" : "Cash Balance",
}

In [16]:
df.rename(columns=rename_dict, inplace=True)

In [17]:
df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517

In [18]:
idx = df[df["Local Body"] == "Harinagar Rural Municipality"].index[0]
idx

np.int64(136)

In [19]:
df_province1 = df.iloc[:138, :].copy()
df_province1

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517
...,...,...,...,...,...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,28.293281,31.165162,0.0,59.458443,20.525654,20.33353,0.0,40.859184,17.222297
134,135,Barju Rural Municipality,34.422993,13.119386,0.0,47.542379,27.443078,8.139141,0.0,35.58222,11.359134
135,136,Bhokraha Rural Municipality,26.706555,21.8664,0.0,48.572955,23.000567,17.954467,0.0,40.955034,2.647668
136,137,Harinagar Rural Municipality,26.660867,28.029786,0.0,54.690653,22.02033,20.121998,0.0,42.142328,12.253008
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518,4128.543863,2574.43002,7.968455,6710.942339,1387.038128

In [20]:
df_province1.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517

In [21]:
df_province1.tail()

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
133,134,Dewangunj Rural Municipality,28.293281,31.165162,0.0,59.458443,20.525654,20.33353,0.0,40.859184,17.222297
134,135,Barju Rural Municipality,34.422993,13.119386,0.0,47.542379,27.443078,8.139141,0.0,35.58222,11.359134
135,136,Bhokraha Rural Municipality,26.706555,21.8664,0.0,48.572955,23.000567,17.954467,0.0,40.955034,2.647668
136,137,Harinagar Rural Municipality,26.660867,28.029786,0.0,54.690653,22.02033,20.121998,0.0,42.142328,12.253008
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518,4128.543863,2574.43002,7.968455,6710.942339,1387.038128

In [22]:
df.columns

Index(['SN', 'Local Body', 'Recurrent', 'Capital', 'Financial', 'Total',
       'Recurrent', 'Capital', 'Financial', 'Total', 'Cash Balance'],
      dtype='object')

In [23]:
df_province1.iloc[:, :6]

,SN,Local Body,Recurrent,Capital,Financial,Total
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779
...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,28.293281,31.165162,0.0,59.458443
134,135,Barju Rural Municipality,34.422993,13.119386,0.0,47.542379
135,136,Bhokraha Rural Municipality,26.706555,21.8664,0.0,48.572955
136,137,Harinagar Rural Municipality,26.660867,28.029786,0.0,54.690653
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518

In [24]:
budget_df = df_province1.iloc[:, list(range(6)) + [10]].copy()
budget_df

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,2.881517
...,...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,28.293281,31.165162,0.0,59.458443,17.222297
134,135,Barju Rural Municipality,34.422993,13.119386,0.0,47.542379,11.359134
135,136,Bhokraha Rural Municipality,26.706555,21.8664,0.0,48.572955,2.647668
136,137,Harinagar Rural Municipality,26.660867,28.029786,0.0,54.690653,12.253008
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518,1387.038128

In [25]:
expenditure_df = df_province1.iloc[:, list(range(2)) + list(range(6, 11))].copy()
expenditure_df

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,23.587589,15.188281,0.0,38.775871,2.881517
...,...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,20.525654,20.33353,0.0,40.859184,17.222297
134,135,Barju Rural Municipality,27.443078,8.139141,0.0,35.58222,11.359134
135,136,Bhokraha Rural Municipality,23.000567,17.954467,0.0,40.955034,2.647668
136,137,Harinagar Rural Municipality,22.02033,20.121998,0.0,42.142328,12.253008
137,Province 1 Total,,4128.543863,2574.43002,7.968455,6710.942339,1387.038128

In [26]:
expenditure_df.describe()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
count,138,138,138.000000,138.000000,138.0,138.00000,138.000000
unique,138,136,138.000000,138.000000,8.0,138.00000,138.000000
top,1,Sunkoshi Rural Municipality,34.104109,24.514032,0.0,58.61814,7.666711
freq,1,2,1.000000,1.000000,131.0,1.00000,1.000000

In [27]:
budget_df.describe()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
count,138,138,138.000000,138.000000,138.0,138.000000,138.000000
unique,138,136,138.000000,138.000000,7.0,138.000000,138.000000
top,1,Sunkoshi Rural Municipality,38.550184,26.144191,0.0,64.694376,7.666711
freq,1,2,1.000000,1.000000,131.0,1.000000,1.000000

### Modular implementation is required for reusability

In [28]:
df

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517
...,...,...,...,...,...,...,...,...,...,...,...
762,751,Joshipur Rural Municipality,32.747868,23.84623,0.0,56.594098,27.2795,17.450748,0.0,44.730248,8.309407
763,752,Bardgoria Rural Municipality,29.301354,18.072167,0.0,47.373521,24.572328,10.642243,0.0,35.214571,8.282966
764,753,Mohanyal Rural Municipality,31.348901,19.7331,0.0,51.082001,27.424238,17.11161,0.0,44.535848,4.147401
765,Sudurpaschim Province Total,,3062.187398,2068.968939,0.4231,5131.579438,2667.222757,1559.780752,0.405687,4227.409196,544.253354
766,Grand Total,,28817.041524,24415.999125,65.324974,53298.365623,23487.310176,15629.985685,26.332561,39143.628422,10156.757357

In [29]:
idx = df[df["SN"] == "Sudurpaschim Province"].index[0]
idx

np.int64(676)

In [30]:
from feature_extraction import FeatureExtraction

In [31]:
file_path = "../data/Expenditure-of-local-bodies.xlsx"
Fext = FeatureExtraction(fname=file_path, province_name="Province 1")

In [32]:
budget_df, expenditure_df = Fext.fit()

Original DataFrame:   Province 1                          Unnamed: 1  Unnamed: 2  Unnamed: 3  \
0          1              Phungling Municipality   38.550184   26.144191
1          2  Aathrai Tribeni Rural Municipality   26.792690   22.705015
2          3    Phaktanglung  Rural Municipality   30.862931   15.232376
3          4      Mikwakhola  Rural Municipality   20.730677   11.014579
4          5       Meringdeng Rural Municipality   26.518959   16.155819

   Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0         0.0   64.694376   34.104109   24.514032         0.0   58.618140
1         0.0   49.497705   21.729910   13.335082         0.0   35.064991
2         0.0   46.095307   24.071506   12.591538         0.0   36.663044
3         0.0   31.745256   16.349711    8.581009         0.0   24.930720
4         0.0   42.674779   23.587589   15.188281         0.0   38.775871

   Unnamed: 10
0     7.666711
1    12.857007
2     7.179870
3     6.718961
4     2.881517
Renamed DataFrame:   SN                          Local Body  Recurrent    Capital Financial  \
0  1              Phungling Municipality  38.550184  26.144191       0.0
1  2  Aathrai Tribeni Rural Municipality   26.79269  22.705015       0.0
2  3    Phaktanglung  Rural Municipality  30.862931  15.232376       0.0
3  4      Mikwakhola  Rural Municipality  20.730677  11.014579       0.0
4  5       Meringdeng Rural Municipality  26.518959  16.155819       0.0

       Total  Recurrent    Capital Financial      Total Cash Balance
0  64.694376  34.104109  24.514032       0.0   58.61814     7.666711
1  49.497705   21.72991  13.335082       0.0  35.064991    12.857007
2  46.095307  24.071506  12.591538       0.0  36.663044      7.17987
3  31.745256  16.349711   8.581009       0.0   24.93072     6.718961
4  42.674779  23.587589  15.188281       0.0  38.775871     2.881517

In [33]:
budget_df

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,2.881517
...,...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,28.293281,31.165162,0.0,59.458443,17.222297
134,135,Barju Rural Municipality,34.422993,13.119386,0.0,47.542379,11.359134
135,136,Bhokraha Rural Municipality,26.706555,21.8664,0.0,48.572955,2.647668
136,137,Harinagar Rural Municipality,26.660867,28.029786,0.0,54.690653,12.253008
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518,1387.038128

In [34]:
expenditure_df

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,23.587589,15.188281,0.0,38.775871,2.881517
...,...,...,...,...,...,...,...
133,134,Dewangunj Rural Municipality,20.525654,20.33353,0.0,40.859184,17.222297
134,135,Barju Rural Municipality,27.443078,8.139141,0.0,35.58222,11.359134
135,136,Bhokraha Rural Municipality,23.000567,17.954467,0.0,40.955034,2.647668
136,137,Harinagar Rural Municipality,22.02033,20.121998,0.0,42.142328,12.253008
137,Province 1 Total,,4128.543863,2574.43002,7.968455,6710.942339,1387.038128

In [35]:
featureextraction = FeatureExtraction(fname=file_path, province_name="Madesh Province")
budget_df, expenditure_df = featureextraction.fit()

Original DataFrame:   Province 1                          Unnamed: 1  Unnamed: 2  Unnamed: 3  \
0          1              Phungling Municipality   38.550184   26.144191
1          2  Aathrai Tribeni Rural Municipality   26.792690   22.705015
2          3    Phaktanglung  Rural Municipality   30.862931   15.232376
3          4      Mikwakhola  Rural Municipality   20.730677   11.014579
4          5       Meringdeng Rural Municipality   26.518959   16.155819

   Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0         0.0   64.694376   34.104109   24.514032         0.0   58.618140
1         0.0   49.497705   21.729910   13.335082         0.0   35.064991
2         0.0   46.095307   24.071506   12.591538         0.0   36.663044
3         0.0   31.745256   16.349711    8.581009         0.0   24.930720
4         0.0   42.674779   23.587589   15.188281         0.0   38.775871

   Unnamed: 10
0     7.666711
1    12.857007
2     7.179870
3     6.718961
4     2.881517
Renamed DataFrame:   SN                          Local Body  Recurrent    Capital Financial  \
0  1              Phungling Municipality  38.550184  26.144191       0.0
1  2  Aathrai Tribeni Rural Municipality   26.79269  22.705015       0.0
2  3    Phaktanglung  Rural Municipality  30.862931  15.232376       0.0
3  4      Mikwakhola  Rural Municipality  20.730677  11.014579       0.0
4  5       Meringdeng Rural Municipality  26.518959  16.155819       0.0

       Total  Recurrent    Capital Financial      Total Cash Balance
0  64.694376  34.104109  24.514032       0.0   58.61814     7.666711
1  49.497705   21.72991  13.335082       0.0  35.064991    12.857007
2  46.095307  24.071506  12.591538       0.0  36.663044      7.17987
3  31.745256  16.349711   8.581009       0.0   24.93072     6.718961
4  42.674779  23.587589  15.188281       0.0  38.775871     2.881517

In [36]:
budget_df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
139,138,Kanchanrup Municipality,72.482428,13.168177,0.0,85.650604,15.487937
140,139,Khadak Municipality,41.580685,29.138886,0.0,70.719571,29.876324
141,140,Dakneshwori Municipality,45.146237,26.284339,0.01,71.440575,17.701542
142,141,Bodebarsign Municipality,43.267243,30.815599,0.0,74.082842,11.724396
143,142,Rajbiraj Municipality,56.850327,27.913272,0.0,84.763599,19.59698