In [1]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..','..')))

In [3]:
from feature_engineering import FeatureExtraction
import pandas as pd

In [ ]:
file_path = "../../data/Expenditure-of-local-bodies.xlsx"
if not os.path.exists(file_path):
    print("Dataset not found!")
else:
    print("Good to go!")

Good to go!

In [5]:
feature_extraction = FeatureExtraction(fname=file_path, province_name="Province 1")
df = feature_extraction.open_file()
df.head()

,Province 1,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.618140,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.792690,22.705015,0.0,49.497705,21.729910,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.179870
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.930720,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517

In [6]:
df = feature_extraction.rename_label(dataframe=df)
df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517

In [7]:
idx_for_total = df[df["SN"] == "Province 1 Total"].index[0]
idx_for_total

np.int64(137)

In [8]:
# Let's find indexes for total 
index_names = ["Province 1 Total",
               "Madesh Province Total",
               "Bagmati Province Total",
               "Gandaki Province Total",
               "Lumbini Province Total",
               "Karnali Province Total",
               "Sudurpaschim Province Total"]
index_names

['Province 1 Total',
 'Madesh Province Total',
 'Bagmati Province Total',
 'Gandaki Province Total',
 'Lumbini Province Total',
 'Karnali Province Total',
 'Sudurpaschim Province Total']

In [24]:
idx_positions = []
for index_name in index_names:
    idx_for_total = df[df["SN"] == index_name].index[0]
    idx_positions.append(idx_for_total)

idx_positions

[np.int64(137),
 np.int64(275),
 np.int64(396),
 np.int64(483),
 np.int64(594),
 np.int64(675),
 np.int64(765)]

In [10]:
df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,23.587589,15.188281,0.0,38.775871,2.881517

In [11]:
df_expense = feature_extraction.extract_expenditure_frame(df)
df_expense.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,23.587589,15.188281,0.0,38.775871,2.881517

In [12]:
# in case of rows -list of index positions is required
# in case of columns - all required except local bodies 
# SN should be renamed by Province 
required_indexes = idx_positions
new_df = df.iloc[required_indexes].copy()
new_df.head(8)

,SN,Local Body,Recurrent,Capital,Financial,Total,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,,5081.831834,3874.215984,10.0477,8966.095518,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,,4734.203008,4193.549548,1.4616,8929.214156,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,,5738.416834,6653.583849,44.8226,12436.823283,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,,3214.196403,2287.84544,2.71,5504.751844,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,,4493.042024,3640.922365,5.278074,8139.242463,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,,2493.164023,1696.912999,0.5819,4190.658922,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,,3062.187398,2068.968939,0.4231,5131.579438,2667.222757,1559.780752,0.405687,4227.409196,544.253354

In [13]:
expense_total_df = df_expense.iloc[idx_positions].copy()
expense_total_df.head(8)

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,,2667.222757,1559.780752,0.405687,4227.409196,544.253354

In [14]:
expense_total_df = expense_total_df.rename(columns={"SN" : "Province"})
expense_total_df.head(8)

,Province,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,,2667.222757,1559.780752,0.405687,4227.409196,544.253354

In [15]:
# Next step is to remove "Local Body" column 
expense_total_df = expense_total_df.drop("Local Body", axis=1)
expense_total_df.head(8)

,Province,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,2667.222757,1559.780752,0.405687,4227.409196,544.253354

### which is the required data_frame

### Testing the implementation

In [16]:
budget_df, expense_df = feature_extraction.extract_individual()

Original data extracted successfully☺️
DataFrame Renamed successfully☺️
ALL THE OPERSTIONS WERE SUCCESSFUL😊

In [17]:
budget_df.head(8)

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,38.550184,26.144191,0.0,64.694376,7.666711
1,2,Aathrai Tribeni Rural Municipality,26.79269,22.705015,0.0,49.497705,12.857007
2,3,Phaktanglung Rural Municipality,30.862931,15.232376,0.0,46.095307,7.17987
3,4,Mikwakhola Rural Municipality,20.730677,11.014579,0.0,31.745256,6.718961
4,5,Meringdeng Rural Municipality,26.518959,16.155819,0.0,42.674779,2.881517
5,6,Mauwakhola Rural Municipality,21.46895,14.5531,0.0,36.02205,4.327077
6,7,Pathibhara Yangwarak Rural Municipality,27.369047,21.029567,0.0,48.398614,6.686506
7,8,Sidingwa Rural Municipality,30.86315,12.018302,0.0,42.881452,5.39351

In [22]:
from feature_engineering import FeatureExtractionTotal

In [23]:
features_extraction_total = FeatureExtractionTotal(budget_frame=budget_df, exp_frame=expense_df)
indexes = features_extraction_total.extract_index_for_total()
indexes

IndexError: index 0 is out of bounds for axis 0 with size 0

### Debugging

In [55]:
import pandas as pd

class FeatureExtractionTotal:
    """Extracts frame for total budget and total expenditure"""
    
    def __init__(self, budget_frame: pd.DataFrame, exp_frame: pd.DataFrame):
        self.budget_frame = budget_frame
        self.exp_frame = exp_frame

    def extract_index_for_total(self) -> list:
        """Extract index for total and return list"""
        index_names = [
            "Province 1 Total",
            "Madesh Province Total",
            "Bagmati Province Total",
            "Gandaki Province Total",
            "Lumbini Province Total",
            "Karnali Province Total",
            "Sudurpaschim Province Total"
        ]
        indexes = []
        
        for idx, province in enumerate(index_names):
            # Get rows matching the current province
            province_rows = self.budget_frame[self.budget_frame["SN"] == province]
            
            if province_rows.empty:
                # If province is missing, print a message and skip this iteration
                print(f"Name is missing: {province}")
                continue  # Skip this province if it's missing
            
            # Get the index of the first matching row
            index_value = province_rows.index[0]
            indexes.append(index_value)
        
        return indexes
    
    def extract_total(self):
        # Get the indexes for the total provinces
        indexes = self.extract_index_for_total()
        
        print("Index extracted 😍")
        
        # Extract total budget and expenditure frames based on the indexes
        total_budget_df = self.budget_frame.iloc[indexes]
        total_exp_df = self.exp_frame.iloc[indexes]
        
        print("Frame for total extracted 😍")
        
        # Rename the 'SN' column to 'Province' for clarity
        total_budget_df = total_budget_df.rename(columns={"SN": "Province"})
        total_exp_df = total_exp_df.rename(columns={"SN": "Province"})
        
        # Remove the 'Local Body' column as it is not required
        total_budget_df = total_budget_df.drop("Local Body", axis=1, errors='ignore')
        total_exp_df = total_exp_df.drop("Local Body", axis=1, errors='ignore')
        
        print("Successful 😍")
        
        return total_budget_df, total_exp_df

In [50]:
features_extraction_total = FeatureExtractionTotal(budget_frame=budget_df, exp_frame=expense_df)
indexes = features_extraction_total.extract_index_for_total()
indexes
#budget_df["Madesh Province Total"]

[np.int64(137),
 np.int64(275),
 np.int64(396),
 np.int64(483),
 np.int64(594),
 np.int64(675),
 np.int64(765)]

In [ ]:
budget_df_total = budget_df.iloc[indexes]
budget_df_total.head(8)

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,,2667.222757,1559.780752,0.405687,4227.409196,544.253354

In [57]:
expense_df.head()

,SN,Local Body,Recurrent,Capital,Financial,Total,Cash Balance
0,1,Phungling Municipality,34.104109,24.514032,0.0,58.61814,7.666711
1,2,Aathrai Tribeni Rural Municipality,21.72991,13.335082,0.0,35.064991,12.857007
2,3,Phaktanglung Rural Municipality,24.071506,12.591538,0.0,36.663044,7.17987
3,4,Mikwakhola Rural Municipality,16.349711,8.581009,0.0,24.93072,6.718961
4,5,Meringdeng Rural Municipality,23.587589,15.188281,0.0,38.775871,2.881517

In [66]:
def find_idx(expense_df: pd.DataFrame) -> list:    
    index_names = [
                "Province 1 Total",
                "Madesh Province Total",
                "Bagmati Province Total",
                "Gandaki Province Total",
                "Lumbini Province Total",
                "Karnali Province Total",
                "Sudurpaschim Province Total"
            ]
    indexes = []
    for province in index_names:
        print(province)
        idx = expense_df[expense_df["SN"] == province].index[0]
        indexes.append(idx)

    return indexes

In [85]:
idx = find_idx(expense_df=expense_df)
idx

Province 1 Total
Madesh Province Total
Bagmati Province Total
Gandaki Province Total
Lumbini Province Total
Karnali Province Total
Sudurpaschim Province Total

[np.int64(137),
 np.int64(275),
 np.int64(396),
 np.int64(483),
 np.int64(594),
 np.int64(675),
 np.int64(765)]

In [69]:
def ret_idx(name : str, dataframe: pd.DataFrame):
    idx = dataframe[dataframe['SN'] == name].index[0]
    return idx

In [77]:
def value_to_check(name: str, dataframe: pd.DataFrame) -> bool:
    if name in dataframe['SN'].values:
        return True
    else:
        return False

In [82]:
expense_df = feature_extraction.extract_expenditure_frame(df)

In [84]:
value_to_check("Bagmati Province Total", expense_df)

True

In [86]:
features_extraction_total = FeatureExtractionTotal(budget_frame=feature_extraction.extract_budget_frame(df),
                                                   exp_frame=feature_extraction.extract_expenditure_frame(df))
budget_df_total, expense_total_df = features_extraction_total.extract_total()

Index extracted 😍
Frame for total extracted 😍
Successful 😍

In [87]:
budget_df_total.head()

,Province,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,5081.831834,3874.215984,10.0477,8966.095518,1387.038128
275,Madesh Province Total,4734.203008,4193.549548,1.4616,8929.214156,1622.605338
396,Bagmati Province Total,5738.416834,6653.583849,44.8226,12436.823283,3564.238124
483,Gandaki Province Total,3214.196403,2287.84544,2.71,5504.751844,1019.491616
594,Lumbini Province Total,4493.042024,3640.922365,5.278074,8139.242463,1514.624353

In [89]:
expense_total_df.head(8)

,Province,Recurrent,Capital,Financial,Total,Cash Balance
137,Province 1 Total,4128.543863,2574.43002,7.968455,6710.942339,1387.038128
275,Madesh Province Total,3722.235995,2597.386723,0.53,6320.152718,1622.605338
396,Bagmati Province Total,4475.180139,3760.083081,12.041037,8247.304257,3564.238124
483,Gandaki Province Total,2658.053799,1459.542216,0.449921,4118.045936,1019.491616
594,Lumbini Province Total,3687.331647,2491.13966,4.728961,6183.200267,1514.624353
675,Karnali Province Total,2148.741976,1187.623233,0.2085,3336.573709,504.506444
765,Sudurpaschim Province Total,2667.222757,1559.780752,0.405687,4227.409196,544.253354

### Perfectly working now